progress_storage:
  threads: 2

partial_progress_storage:
  threads: 2

gui:
  rows: 6
  page-size: 45
  max-pages: 100
  navigation:
    previous:
      slot: "6,3"
      material: "ARROW"
      model_name: ""
      custom_model_data: 0
    next:
      slot: "6,7"
      material: "ARROW"
      model_name: ""
      custom_model_data: 0
    other:
      slot: "6,5"
      enabled: false
      material: "PAPER"
      model_name: ""
      custom_model_data: 0
      execute-commands:
        - "say You are on page {page_number} of {max_pages}."